apiVersion: apps/v1  
kind: Deployment
metadata:
  name: tododataservice 
  namespace: todoapp-namespace
  labels:
    app: tododataservice
spec:
  selector:
    matchLabels: 
      app: tododataservice
  replicas: 1     
  template: 
    metadata:
      labels:
        app: tododataservice
    spec: 
      containers:
        - name: todolistdataservice
          image: fthsev/todolistdataservice:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_STRING
              value: "host=postgres;port=5432;username=postgres;password=1234"
---
apiVersion: v1
kind: Service        
metadata:
  name: todolistdataservice 
  namespace: todoapp-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 3000       
      targetPort: 80
      nodePort: 30080
  selector: 
    app: tododataservice