version: '3.4'

networks:
  todoapi-dev:
    driver: bridge

services:
  dataservice:
    image: fthsev/todolistdataservice:latest
    depends_on:
      - "postgres_image"
    ports:
      - "3000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;username=postgres;password=1234"
    networks:
      - todoapi-dev
  
  uiservice:
    image: fthsev/todolistuiservice:latest
    depends_on:
      - "dataservice"
    ports:
      - "4200:80"
    networks:
      - todoapi-dev
        
    
  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always 
    environment:
      POSTGRES_PASSWORD: "1234"
    networks:
      - todoapi-dev

