apiVersion: apps/v1  
kind: Deployment
metadata:
  name: postgres 
  namespace: todoapp-namespace
  labels:
    app: postgres
spec:
  selector:
    matchLabels:     
      app: postgres
  replicas: 1        
  template:          
    metadata:
      labels:        
        app: postgres 
    spec:           
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"         
---
apiVersion: v1
kind: Service        
metadata:
  name: postgres 
  namespace: todoapp-namespace
spec:
  type: NodePort
  ports:
    - port: 5432       
      targetPort: 5432
      nodePort: 30432
  selector:          
    app: postgres